### ISSUE TITLE
0 active connections to the XP network?

### ISSUE THREAD

**Issue by UcMeIcU** [eXperiencePoints/XPCoin#11]
Why does the Windows install of the wallet not connect to the XP network? When I open the wallet, on the bottom right I get two small screens with a red "x" on them which when I hover over them says "0 active connections to the XP Network"
![xp network connection](https://user-images.githubusercontent.com/20422513/34231439-133d5a68-e5aa-11e7-95b5-28e136d34499.PNG)

**Comment by SOELexicon** [comment]
fixed with https://github.com/eXperiencePoints/XPCoin/commit/fab2f2c1a156a8d28301c5376104f19c0213b50f

just need to compile the QT
