### ISSUE TITLE
38.81M Stake weight bug

### ISSUE THREAD

**Issue by BinkersSoft** [eXperiencePoints/XPCoin#2]
This wallet has the "38.81M Bug" If stake weight reaches 38.81M the reward will become negative and then move back up to 0 which happens at stake weight ~77.62M stake weight and will move up in the postive range until stake weight ~116.43M and it will back to negative value.....basically an integer overflow bug. Workaround for users is to use small inputs but it is only short term. As supply and staking difficulty increases it will be a huge problem. The only two fixes I know of are one reduce supply which we already established is undesireable as the supply is intentional and second change affected variables to (u)nint160 or (u)int256 depending how far the supply is expected to grow.

Most users will not be affected by this UNTIL difficulty jumps up and it will as XP gets attention. Now you might be thinknig we are at approx 208B supply and so far it hasn't been an issue...that is only true cause only 25% or approx 50B coins are actively staking

Here is a github bug on Ember https://github.com/EmberCoin/Ember/issues/15 so you can search the code where it is likely being affected as the bug is identical to what is affecting Ember but with a proposed fix that I don't recommend as it is very much a band aid fix (Ember devs agreed) in my opinion and involves adding a float to the equation for an integer variable. As I understand it, float operations can't be guaranteed across hardware platforms and could cause unintentional forks between hardware as the coin becomes more cross platform. 

I also screen shot some examples of how the current QT wallet confirms the bug exists as it shows end of period reward less than initial period reward and end of period negative reward. Also do excelerate the testing I used a single 30M input.

This is my first time posting an issue on github and I hope it is appropriate. I also welcome any suggestions to make it better or questions if you need more info.

![2017-09-30_14_24_09-xp_-_wallet](https://user-images.githubusercontent.com/25735478/31052589-dc1c74b8-a645-11e7-9fbe-fcea61d9bbae.png)
![2017-09-30_14_24_31-xp_-_wallet](https://user-images.githubusercontent.com/25735478/31052587-dc105f48-a645-11e7-99f1-97f723839afc.png)
![2017-09-30_14_25_25-xp_-_wallet](https://user-images.githubusercontent.com/25735478/31052588-dc16aa10-a645-11e7-888c-2fe7da1e51c3.png)
![2017-09-30_14_25_38-xp_-_wallet](https://user-images.githubusercontent.com/25735478/31052586-dc0f8a28-a645-11e7-84ac-2cb031e95187.png)

**Comment by neetpill** [comment]
This issue was fixed in the recent fork (https://github.com/eXperiencePoints/XPCoin/commit/923c993051e9e8bc89a2c67db6631abc932d2fd9)
