### ISSUE TITLE
wallet hangs on boot at "loading block index"

### ISSUE THREAD

**Issue by fmonts** [eXperiencePoints/XPCoin#21]
Windows 10 64bit, the wallet very often hangs when opened, I waited 30+ minutes, but the only solution is to kill it and reopen again... 

I have also the bitcoin core wallet with the full blockchain and never had this problem

**Comment by kamushadenes** [comment]
Mine stays for a couple seconds on this same message, and then crashes stating "Error loading block database"

**Comment by SOELexicon** [comment]
never build will include a display that shows it loading. you have to leave the wallet loading any interruption makes it halt in windows because its working in the background the foreground window gets unresponsive.
