### ISSUE TITLE
Libssl.so.1.0.0

### ISSUE THREAD

**Issue by uaktags** [eXperiencePoints/XPCoin#4]
Looks like XPCoin requires a very old version of openssl as well:

/root/XP-Linuxd: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by onokatio** [comment]
That problem can be solved like this https://github.com/onokatio/NEETCOIN/commit/3b2bfc58ab6048be803b2cd466d7214cd1eecdfc
