### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by jtumano** [eXperiencePoints/XPCoin#40]
I was able to compile source on my raspberry pi the state from Feb 12 state. 
Today tried to pull latest changes and compile and it didn't. The error shows: 
`/usr/bin/ld: cannot find -ldb_cxx`

I think it is because of this commit: 
commit 689d48386c66cdb1afeb13c34e1503d9390bf4ee

**Comment by Naruto** [comment]
Please give more information.

- which compile did you XPd or XP-Qt?
- your rasberry pi distribution and version.

This commit ( 689d483 ) is for XPd, and cmake build.
If you compiled XP-Qt or used makefile.unix, this commit is not effect.

**Comment by jtumano** [comment]
I compiled XPd on raspberry pi 3 model B+, Raspbian Stretch Lite from official Pi site. 
Berkeley DB4.8 was taken from this thread: 
https://okcashtalk.org/index.php?topic=2025.0
until step 4

Now I've tried to compile on laptop and it was succesful. 
I will try later to compile on raspi clean system starting from scratch and give you more information.

**Comment by jtumano** [comment]
I could compile it succesfully after providing static libs path. 

For information if someone will occur same problems: 
after compiling db4.8 make some more steps: 
Tell your system where to find db4.8
```
export BDB_INCLUDE_PATH="/usr/local/BerkeleyDB.4.8/include"
export BDB_LIB_PATH="/usr/local/BerkeleyDB.4.8/lib"
ln -s /usr/local/BerkeleyDB.4.8/lib/libdb-4.8.so /usr/lib/libdb-4.8.so

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/BerkeleyDB.4.8.NC/lib"
```

Closing this also because it's not a wallet issue
